### ISSUE TITLE
Formatting issues on mobile [UNREPLICATED]

### ISSUE THREAD

**Issue by dr3gos** [nlanson/AUCB#4] opened 2021-04-20 14:28 UTC
![Screenshot_20210420-172714_Reddit](https://user-images.githubusercontent.com/68168588/115413370-c642da80-a1fd-11eb-9509-c125437dcbb0.jpg)
![Screenshot_20210420-172709_Reddit](https://user-images.githubusercontent.com/68168588/115413376-c7740780-a1fd-11eb-8ea1-6c050f3e24a0.jpg)

**Comment by nlanson** [comment] 2021-04-20 14:35
Good evening, 

I am on iOS Reddit and have no issues with the bot's formatting.

On my side, it looks like this:
![image](https://user-images.githubusercontent.com/34389972/115414763-ab8e5700-a239-11eb-87e5-fd721691e9b2.jpeg)


Could you provide me details on what client and device you are using so I can try and replicate this issue. 

Also, when did you first notice this issue? Was it pre or post implementation of the new formatting?

Thanks

**Comment by nlanson** [comment] 2021-04-21 09:41
Wrapped the ASCII in code blocks in dce42deffcd52635370ba2e222069b2c0352d52c.

Could you please see if the text is formatting correctly now.

Examples:
[Vanilla](https://www.reddit.com/user/AmongUsCockBot/comments/mlwbuz/bot_info/gvb10rh/?context=3)
[Snek](https://www.reddit.com/user/AmongUsCockBot/comments/mlwbuz/bot_info/gvb0bb0/?context=3)
[Dynamic](https://www.reddit.com/user/AmongUsCockBot/comments/mlwbuz/bot_info/gvb0yzd/?context=3)

**Comment by Lachcim** [comment] 2021-04-21 18:27
Just chiming in to advise you not to use the triple-tilde or triple-backtick syntax for code blocks. On old Reddit, it renders like this:

![Screenshot 2021-04-21 202344](https://user-images.githubusercontent.com/15709471/115602785-9f5cd500-a2df-11eb-80ef-e56c2efa95fc.png)

I believe the only platform-independent way to trigger code blocks is the four-space syntax.

**Comment by Lachcim** [comment] 2021-04-21 19:04
Commenters in the Reddit thread have reported that the double-space line break doesn't work on the official Android Reddit app. I can confirm that this is the case, see the first line in the screenshot below.

Furthermore, I was able to verify that the four-space code block resolves the issue on:

* The official Android app
* Old Reddit
* New Reddit
* .compact
* The mobile website, including amp.reddit.com

![a](https://user-images.githubusercontent.com/15709471/115607314-1fd20480-a2e5-11eb-897b-3b8a76c0bbd8.png)


Sloppy testing on our part but hopefully we can quickly fix it.

**Comment by nlanson** [comment] 2021-04-21 21:37
Thanks again. 

As I do not hold the means to test on android devices I was using trial and error and asking users who had the formatting issue to try and find a fix. 

It seems the 4-spaces method was the solution I was looking for. 

Will merge, test and put into production asap.

**Comment by nlanson** [comment] 2021-04-21 23:28
#5 and #6 close this issue. 
Hopefully, no more formatting issues arise.

**Closed as completed by nlanson** 2021-04-21 23:28 UTC
Labels: bug
